# Generated by Django 3.0.8 on 2020-07-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('P', 'Physics'), ('G', 'Geometry'), ('C', 'Chemistry')], max_length=1)),
                ('duration', models.IntegerField()),
                ('tests_desc', models.CharField(max_length=500)),
                ('study_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
