# Generated by Django 3.0.8 on 2020-07-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='items',
            field=models.ManyToManyField(to='study.Item'),
        ),
    ]
