# Generated by Django 3.0.8 on 2020-07-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_day_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
