# Generated by Django 3.0.8 on 2020-07-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='comments',
            field=models.ManyToManyField(to='study.Comment'),
        ),
    ]
