# Generated by Django 3.0.8 on 2020-07-18 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200716_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='students',
            field=models.ManyToManyField(null=True, related_name='s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t', to=settings.AUTH_USER_MODEL),
        ),
    ]
