# Generated by Django 3.0.8 on 2020-07-18 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200718_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='students',
            field=models.ManyToManyField(related_name='s', to=settings.AUTH_USER_MODEL),
        ),
    ]
